### ISSUE TITLE
How to make barcode scanning actions work (iOS)

### ISSUE THREAD

**Issue by jeroen-meijer** [Codenaut/vision_camera#1]
Hi there. I've tried to use your plugin example to get the barcode scanning working.

## Steps to Reproduce

I downloaded the package, did a `flutter packages get` and replaced line 60 with the following:
```dart
...
                controller =
                    new CameraController(newValue, ResolutionPreset.high, OptionsAndEventTestClass.options);
                await controller.initialize();
...
```

I made a class, `OptionsAndEventTestClass` that returns the options that the controller asks for (from reading the `camera.dart` file and reverse-engineering it):
```dart
import 'package:flutter/material.dart';
import 'package:vision_camera/vision_camera.dart';

class OptionsAndEventTestClass{

  static Map<String, String> get event {
    final Map<String, String> event = <String, String>{};
    event['eventType'] = 'barcodes';
    return event;
  }

  static Map get options {
    final Map<String, Function> options = <String, Function>{};
    options['onBarcodeRead'] = (Iterable<Barcode> barcodes) => barcodes.forEach(
        (Barcode barcode) => debugPrint(
            'BARCODE\n toString:\t${barcode.toString()}\n rawValue:\t${barcode.rawValue}\n format:\t${barcode.format}'));
    return options;
  }
}
```

## Problem
When I run the app, I can see my front- and back-facing cameras. Activating either and taking pictures works, but whenever I put it in front of a QR- or barcode, it doesn't trigger my callback. When breakpointing on the `_listener()` function in the `camera.dart` package, it never gets triggered.

Am I doing something wrong or is this package broken, perhaps?

I need this package (or something similar) for an app that I'm building for a startup, so a quick response would be greatly appreciated.

Thank you in advance.

Best, Jeroen.

## Files

[The `/lib` for the example.](https://github.com/Codenaut/vision_camera/files/1996333/lib.zip)

**Comment by jalpedersen** [comment]
Hi Jeroen

I originally only needed this for an internal project for Android - so iOS support is not implemented yet

**Comment by jeroen-meijer** [comment]
Hi,

No problem, thank you for your time.
